# Generated by Django 6.0.3 on 2026-04-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_alter_language_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=150)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=150)),
                ("year", models.PositiveSmallIntegerField()),
                ("topic", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("event", models.CharField(max_length=200)),
                ("year", models.PositiveSmallIntegerField()),
                ("role", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
