# Generated by Django 6.0.3 on 2026-04-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_certification_presentation_publication_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="project",
            name="stack",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
