# Generated by Django 6.0.3 on 2026-04-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_alter_project_options_alter_project_name_and_more"),
        ("portfolio", "0002_proyecto_remove_casestudy_project_casestudy_proyecto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
