# Generated by Django 5.2 on 2026-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_delete_project"),
    ]

def apply_resilient_schema(apps, schema_editor):
    """
    Aplica las operaciones de esquema de forma resiliente, detectando el motor de base de datos.
    Soporta PostgreSQL (con IF NOT EXISTS) y SQLite (con chequeos manuales).
    """
    connection = schema_editor.connection
    vendor = connection.vendor

    if vendor == 'postgresql':
        # PostgreSQL: Usamos la sintaxis nativa IF NOT EXISTS para máxima seguridad.
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS "cv_project" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "name" varchar(150) NOT NULL,
                "description" text NOT NULL,
                "stack" varchar(200) NOT NULL,
                "repo_url" varchar(200) NOT NULL,
                "featured" boolean NOT NULL
            );
        """)
        # Agregamos las columnas si no existen
        schema_editor.execute('ALTER TABLE "cv_education" ADD COLUMN IF NOT EXISTS "start_year" smallint NULL;')
        schema_editor.execute('ALTER TABLE "cv_experience" ADD COLUMN IF NOT EXISTS "featured" boolean NOT NULL DEFAULT FALSE;')
        schema_editor.execute('ALTER TABLE "cv_experience" ADD COLUMN IF NOT EXISTS "location" varchar(100) NOT NULL DEFAULT \'\';')
        schema_editor.execute('ALTER TABLE "cv_profile" ADD COLUMN IF NOT EXISTS "email" varchar(254) NOT NULL DEFAULT \'\';')

    elif vendor == 'sqlite':
        # SQLite: Creamos la tabla si no existe (SQLite sí soporta IF NOT EXISTS en CREATE TABLE)
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS "cv_project" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "name" varchar(150) NOT NULL,
                "description" text NOT NULL,
                "stack" varchar(200) NOT NULL,
                "repo_url" varchar(200) NOT NULL,
                "featured" bool NOT NULL
            );
        """)
        # Para ALTER TABLE, SQLite no tiene IF NOT EXISTS. Verificamos cada columna.
        def add_col_sqlite(table, column, definition):
            cursor = connection.cursor()
            cursor.execute(f"PRAGMA table_info({table});")
            existing_cols = [row[1] for row in cursor.fetchall()]
            if column not in existing_cols:
                schema_editor.execute(f'ALTER TABLE {table} ADD COLUMN {column} {definition};')

        add_col_sqlite("cv_education", "start_year", "smallint NULL")
        add_col_sqlite("cv_experience", "featured", "bool NOT NULL DEFAULT 0")
        add_col_sqlite("cv_experience", "location", "varchar(100) NOT NULL DEFAULT ''")
        add_col_sqlite("cv_profile", "email", "varchar(254) NOT NULL DEFAULT ''")

def rollback_resilient_schema(apps, schema_editor):
    """Operación de reversión."""
    schema_editor.execute('DROP TABLE IF EXISTS "cv_project";')
    # Nota: Eliminar columnas en SQLite es complejo (no soportado en versiones viejas).
    # Como esta migración es de "emergencia" para corregir desincronización,
    # el rollback se deja como operacion no-op o simple DROP para Postgres.
    if schema_editor.connection.vendor == 'postgresql':
        for table, col in [("cv_education", "start_year"), ("cv_experience", "featured"), 
                           ("cv_experience", "location"), ("cv_profile", "email")]:
            schema_editor.execute(f'ALTER TABLE "{table}" DROP COLUMN IF EXISTS "{col}";')

class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_delete_project"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(apply_resilient_schema, reverse_code=rollback_resilient_schema),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Project",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=150)),
                        ("description", models.TextField()),
                        ("stack", models.CharField(blank=True, max_length=200)),
                        ("repo_url", models.URLField(blank=True)),
                        ("featured", models.BooleanField(default=False)),
                    ],
                ),
                migrations.AddField(
                    model_name="education",
                    name="start_year",
                    field=models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="experience",
                    name="featured",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="experience",
                    name="location",
                    field=models.CharField(blank=True, max_length=100),
                ),
                migrations.AddField(
                    model_name="profile",
                    name="email",
                    field=models.EmailField(blank=True, max_length=254),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="education",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Año de término"),
        ),
    ]
