# Generated by Django 5.2 on 2026-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_delete_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("stack", models.CharField(blank=True, max_length=200)),
                ("repo_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="education",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Año de término"),
        ),
    ]
