# Generated by Django 5.2 on 2026-04-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0006_add_location_featured_startyear_email_textfield"),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "cv_project";',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
