# Generated by Django 6.0.3 on 2026-04-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Lead text shown below the title.", max_length=255
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Preview image for the case study header.",
                        upload_to="portfolio/case_studies/",
                    ),
                ),
                (
                    "skills_applied",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated skill tags (e.g. "Fullstack, DevOps, Git").',
                        max_length=500,
                    ),
                ),
                (
                    "section_1_description",
                    models.TextField(
                        blank=True, verbose_name="1. Breve descripción de la actividad"
                    ),
                ),
                (
                    "section_2_challenge",
                    models.TextField(blank=True, verbose_name="2. Desafío principal"),
                ),
                (
                    "section_3_solution",
                    models.TextField(blank=True, verbose_name="3. Solución propuesta"),
                ),
                (
                    "section_4_tools",
                    models.TextField(
                        blank=True, verbose_name="4. Herramientas técnicas utilizadas"
                    ),
                ),
                (
                    "section_5_learnings",
                    models.TextField(
                        blank=True, verbose_name="5. Principales aprendizajes"
                    ),
                ),
                (
                    "section_6_metrics",
                    models.TextField(blank=True, verbose_name="6. Métricas de impacto"),
                ),
                (
                    "section_7_skills",
                    models.TextField(
                        blank=True, verbose_name="7. Habilidades técnicas aplicadas"
                    ),
                ),
                (
                    "section_8_justification",
                    models.TextField(
                        blank=True, verbose_name="8. Justificación de la elección"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_study",
                        to="cv.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso de Estudio",
                "verbose_name_plural": "Casos de Estudio",
            },
        ),
    ]
