# Generated by Django 6.0.3 on 2026-04-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=200)),
                ("descripcion", models.TextField()),
                ("tecnologias", models.CharField(blank=True, max_length=500)),
                ("url_repositorio", models.URLField(blank=True)),
                ("url_demo", models.URLField(blank=True)),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True,
                        help_text="URL absoluta de la imagen del proyecto (GitHub Pages u otro CDN).",
                    ),
                ),
                ("destacado", models.BooleanField(db_index=True, default=False)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["orden", "-fecha_creacion"],
            },
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="project",
        ),
        migrations.AddField(
            model_name="casestudy",
            name="proyecto",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_study",
                to="portfolio.proyecto",
            ),
        ),
    ]
