# Generated by Django 6.0.3 on 2026-04-02 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_proyecto_remove_casestudy_project_casestudy_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="proyecto",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_study",
                to="portfolio.proyecto",
            ),
            preserve_default=False,
        ),
    ]
