# Generated by Django 6.0.3 on 2026-04-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_casestudy_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="imagen_url",
            field=models.URLField(
                blank=True,
                help_text="URL absoluta de la imagen del proyecto (GitHub Pages u otro CDN).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="tecnologias",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="url_demo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="url_repositorio",
            field=models.URLField(blank=True, null=True),
        ),
    ]
