# Generated by Django 5.2 on 2026-04-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_alter_proyecto_imagen_url_alter_proyecto_tecnologias_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Proyecto",
            new_name="Project",
        ),
    ]
